[package]
name = "test-e2e"
version = "0.1.0"
edition = "2021"

[lib]
name = "mopro_bindings"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "ios"

[[bin]]
name = "android"

[features]
default = ["mopro-ffi/circom"]

[dependencies]
mopro-ffi = { path = "../mopro-ffi" }
num-bigint = "0.4.0"
rust-witness = { git = "https://github.com/vimwitch/rust-witness.git" }
uniffi = "0.28.0"

[build-dependencies]
mopro-ffi = { path = "../mopro-ffi" }
rust-witness = { git = "https://github.com/vimwitch/rust-witness.git" }
uniffi = { version = "0.28.0", features = ["build"] }

[dev-dependencies]
uniffi = { version = "0.28.0", features = ["bindgen-tests"] }
