name: Build and Test

on:
    push:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review

env:
    CARGO_TERM_COLOR: always

jobs:
    # TODO: Add a job to run clippy
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check formatting
              run: cargo fmt --all -- --check

    test-ffi-halo2:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Build package with halo2 config
              run: cd mopro-ffi && cargo build --features halo2 --no-default-features
            ### Halo2 tests will fail until we replace the stub implementation
            ### just build to make sure the flags don't cause errors
            # - name: Run halo2 tests
            #   # TODO: Fix this custom jar thing
            #   run: |
            #       cd mopro-ffi/
            #       curl -L https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar -o jna-5.13.0.jar
            #       CLASSPATH=jna-5.13.0.jar cargo test -- --nocapture
            #       cargo test --features halo2 --no-default-features

    test-ffi-circom:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Run ffi circom tests
              run: cd mopro-ffi && cargo test --features circom --no-default-features
    test-e2e-circom:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Run e2e circom tests
              # TODO: Fix this custom jar thing
              run: |
                  cd test-e2e
                  curl -L https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar -o jna-5.13.0.jar
                  CLASSPATH=jna-5.13.0.jar cargo test -- --nocapture
    test-xcframework-build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Build iOS xcframework
              run: cd test-e2e && cargo run --bin ios
    test-android-ffi-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Build Android bindings
              run: cd test-e2e && cargo run --bin android
